/*Name:Lam Hui Shan
Matric:293384
*/
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lamhuishan
 */
public class BMIForm extends javax.swing.JFrame {
    private int ind;//value of index
    private StudentOperation operation;//call method from StudentOperation class
    private Student stud;//retrieve information from Student class
    /**
     * Creates new form BMIForm
     */
    public BMIForm() {
        initComponents();
        ind=-1;
        operation=new StudentOperation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MatricNoTF = new javax.swing.JTextField();
        NameTF = new javax.swing.JTextField();
        BMITF = new javax.swing.JTextField();
        HeightTF = new javax.swing.JTextField();
        WeightTF = new javax.swing.JTextField();
        StatusTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        calcBillBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        DisplayBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        MasterRB = new javax.swing.JRadioButton();
        DegreeRB = new javax.swing.JRadioButton();
        UniCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Matric Number");

        jLabel3.setText("Name");

        jLabel4.setText("Program");

        jLabel5.setText("University");

        jLabel6.setText("Weight (in KG)");

        jLabel7.setText("Height (in meter)");

        jLabel8.setText("BMI");

        jLabel9.setText("Status");

        MatricNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatricNoTFActionPerformed(evt);
            }
        });

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });

        BMITF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMITFActionPerformed(evt);
            }
        });

        HeightTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightTFActionPerformed(evt);
            }
        });

        WeightTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightTFActionPerformed(evt);
            }
        });

        StatusTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusTFActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        calcBillBtn.setText("Calculate BMI");
        calcBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBillBtnActionPerformed(evt);
            }
        });

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        DisplayBtn.setText("Display All");
        DisplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBtnActionPerformed(evt);
            }
        });

        SearchBtn.setText("Search by Matric No");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(MasterRB);
        MasterRB.setText("Master");

        buttonGroup1.add(DegreeRB);
        DegreeRB.setText("Degree");
        DegreeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DegreeRBActionPerformed(evt);
            }
        });

        UniCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UUM", "UKM", "USM" }));
        UniCB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UniCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(MatricNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(DegreeRB)
                                            .addGap(18, 18, 18)
                                            .addComponent(MasterRB)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StatusTF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BMITF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WeightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HeightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(48, 48, 48)
                                .addComponent(UniCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(7, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calcBillBtn)
                        .addGap(18, 18, 18)
                        .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ResetBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DisplayBtn)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(MatricNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(MasterRB)
                            .addComponent(DegreeRB))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(UniCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(WeightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(HeightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(BMITF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(StatusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcBillBtn)
                    .addComponent(SaveBtn)
                    .addComponent(ResetBtn)
                    .addComponent(DisplayBtn)
                    .addComponent(SearchBtn)
                    .addComponent(UpdateBtn))
                .addGap(21, 21, 21))
        );

        jLabel1.setText("BMI Calculator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatricNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatricNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatricNoTFActionPerformed

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void BMITFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMITFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BMITFActionPerformed

    private void HeightTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightTFActionPerformed

    private void WeightTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightTFActionPerformed

    private void StatusTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusTFActionPerformed

    private void calcBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBillBtnActionPerformed
        // TODO add your handling code here:
        try{
            String matricTF=MatricNoTF.getText();
            if(matricTF.equals(""))
                throw new Exception("Please enter matric number");
            int matric=Integer.parseInt(matricTF);

            String name=NameTF.getText();
            if(name.equals("")){
                throw new Exception("Please enter name.");
            }
            
            String uni=UniCB.getSelectedItem().toString();
            if(DegreeRB.isSelected()==false && MasterRB.isSelected()==false)
                throw new Exception("Please select the program type");

            String program="";
            if(uni.equals("degree"))
                program="degree";
            else
                program="master";

            String weightTF= WeightTF.getText();
            if(weightTF.equals(""))
                throw new Exception ("Please enter the weight");
            Double weight=Double.parseDouble(weightTF);

            String heightTF= HeightTF.getText();
            if(heightTF.equals(""))
                throw new Exception ("Please enter the height");
            Double height=Double.parseDouble(heightTF);


            double bmi=operation.calculateBMI(height, weight);
            String status=operation.getStatusBMI(bmi);

            String BMI=String.format("%.2f", bmi);
            BMITF.setText(BMI);
            StatusTF.setText(status);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please input digits only for weight,height and matric number.");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_calcBillBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        try{
            ind++;
            String matricTF=MatricNoTF.getText();
            if(matricTF.equals(""))
                throw new Exception("Please enter matric number");
            int matric=Integer.parseInt(matricTF);

            String name=NameTF.getText();
            if(name.equals(""))
                throw new Exception ("Please enter name");

            String university=UniCB.getSelectedItem().toString();

            String program="";
            if(DegreeRB.isSelected()==false && MasterRB.isSelected()==false)
                throw new Exception("Please choose the program type");
            if(DegreeRB.isSelected())
                program="degree";
            else
                program="master";
        
            String weightTF= WeightTF.getText();
            if(weightTF.equals(""))
                throw new Exception("Please input weight");
            Double weight=Double.parseDouble(weightTF);

            String heightTF= HeightTF.getText();
            if(heightTF.equals(""))
                throw new Exception("Please input height");
            Double height=Double.parseDouble(heightTF);

            String status=StatusTF.getText();
            if(status.equals(""))
                throw new Exception ("Please press the calculate BMI button before adding information");
            String bmiTF=BMITF.getText();
            Double bmi=Double.parseDouble(bmiTF);
            
            stud=new Student(name, matric, status, university, program, weight, height, bmi);
            operation.saveRecord(ind,stud);
            displayTA.setText("The record has been saved successfully in the array of object");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please input digits only for weight,height and matric number");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        NameTF.setText("");
        MatricNoTF.setText("");
        WeightTF.setText("");
        HeightTF.setText("");
        buttonGroup1.clearSelection();
        displayTA.setText("");
        StatusTF.setText("");
        BMITF.setText("");
        UniCB.setSelectedItem("UUM");
        
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void DisplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBtnActionPerformed
        // TODO add your handling code here:
        String read=operation.readAllrecord();
            displayTA.setText("Name\tMatric No\tProgram\tUniversity\tHeight(m)\tWeight(Kg)\tBMI\tStatus\n"+read);
  
    }//GEN-LAST:event_DisplayBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        try{
            String targetTF=MatricNoTF.getText();
            if(targetTF.equals(""))
                throw new Exception("Please enter the matric number.");
            
            int target=Integer.parseInt(targetTF);
            stud=operation.searchRecord(target);

            if(stud==null){
                displayTA.setText("The record is not found.");
            }else{
                NameTF.setText(stud.getName());
                MatricNoTF.setText(String.valueOf(stud.getMatric()));
                WeightTF.setText(String.valueOf( stud.getWeight()));
                HeightTF.setText(String.valueOf(stud.getHeight()));
                BMITF.setText(String.valueOf(stud.getbmi()));
                StatusTF.setText(stud.getStatus());
                UniCB.setSelectedItem(stud.getUniversity());
                if(stud.getProgram().equals("degree"))
                    buttonGroup1.setSelected(DegreeRB.getModel(), true);
                else
                    buttonGroup1.setSelected(MasterRB.getModel(), true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
   
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        
        try{
            String matricTF= MatricNoTF.getText();
            if(matricTF.equals(""))
                throw new Exception("Please enter matric number");
            int matric=Integer.parseInt(matricTF);

            String name=NameTF.getText();
            if(name.equals(""))
                throw new Exception ("Please enter name");

            String university=UniCB.getSelectedItem().toString();

            String program="";
            if(DegreeRB.isSelected()==false && MasterRB.isSelected()==false)
                throw new Exception("Please choose the program type");
            if(DegreeRB.isSelected())
                program="degree";
            else
                program="master";
        
            String weightTF= WeightTF.getText();
            if(weightTF.equals(""))
                throw new Exception("Please input weight");
            Double weight=Double.parseDouble(weightTF);

            String heightTF= HeightTF.getText();
            if(heightTF.equals(""))
                throw new Exception("Please input height");
            Double height=Double.parseDouble(heightTF);

            String status=StatusTF.getText();
            if(status.equals(""))
                throw new Exception ("Please press the calculate BMI button before updating information");
            String bmiTF=BMITF.getText();
            Double bmi=Double.parseDouble(bmiTF);
            
            displayTA.setText(operation.updateRecord(name,matric,height,weight,bmi,program,university,status));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void UniCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UniCBActionPerformed

    private void DegreeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DegreeRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DegreeRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMIForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BMITF;
    private javax.swing.JRadioButton DegreeRB;
    private javax.swing.JButton DisplayBtn;
    private javax.swing.JTextField HeightTF;
    private javax.swing.JRadioButton MasterRB;
    private javax.swing.JTextField MatricNoTF;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField StatusTF;
    private javax.swing.JComboBox<String> UniCB;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JTextField WeightTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcBillBtn;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
